print("My Age: " + str(12))

#ADDITION
print(123 + 456)

#SUBSTRACTION
print(3  - 2)

# MULTIPLICATION
print( 4 * 2)

#DIVISION
print(8 / 2)

#DIVISION WITH ROUNDING OFF
print( 5 // 2)
print(5 / 2)

#SQUARE
print(2**3)

#RULES OF PRIORITY FOR MAHTEMATICAL OPERASTIONS
# PEMDAS = PARENTHESIS , EXPONENT , MULTIPLICATION , DIVISION , ADDITION , SUBSTRACTION (ALSO THE SAME CONCEPT OF BODMAS)
print(3 * 3 + 3 / 3 - 3)  #the calculation of this ALWAYS GOES FROM LEFT TO RIGHT , IF HTEY HAVE THE SAME PRIORITY


#TASK : MODIFY THE CODE  " print(3 * 3 + 3 / 3 - 3)  " TO GET THE OUTPUT 3?
print(3*(3+3)/3-3)